targets:
  $default:
    builders:
      json_serializable:
        options:
          # JSON 직렬화 옵션
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      
      freezed:
        options:
          # Freezed 옵션
          map: true
          when: true
          maybe_map: true
          maybe_when: true
          copy_with: true
          equal: true
          to_string: true
          from_json: true
          to_json: true
